---
- name: Install and start HTTP service
  hosts: login
  become: yes

  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: present

  - name: Start httpd service
    service:
      name: httpd
      state: started
      enabled: yes
